name: Build Pulsar Binaries

on:
  workflow_call:
    inputs:
      from_ci:
        type: boolean
        required: false
        default: true
      VERSION:
        type: string
        required: true

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build x86_64
        env:
          PKGVER: ${{ inputs.VERSION }}
          ARCH: x86-64
        run: |
          sed -i "s/\(pkgver=\"\)[^\"]*\"/\1$PKGVER\"/" PKGBUILD
          sed -i "s/\(arch=(\"\)[^\")]*\"/\1x86_64\"/" PKGBUILD
          bash build.sh

      - name: Build x86_64-v3
        env:
          PKGVER: ${{ inputs.VERSION }}
          ARCH: x86-64-v3
        run: |
          sed -i "s/\(pkgver=\"\)[^\"]*\"/\1$PKGVER\"/" PKGBUILD
          sed -i "s/\(arch=\"\)[^\"]*\"/\1x86_64_v3\"/" PKGBUILD
          bash build.sh

      - name: Get Release Description
        id: description
        run: |
          echo -e $(curl -s https://api.github.com/repos/pulsar-edit/pulsar/releases/latest | jq -r '.body') > build.md
          DELIM="$(openssl rand -hex 8)"
          echo "BUILD_LOG<<${DELIM}" >> "$GITHUB_OUTPUT"
          cat build.md >> "$GITHUB_OUTPUT"
          echo "${DELIM}" >> "$GITHUB_OUTPUT"

      - name: Get Tag
        id: build_tag
        run: |
          TAG="v${{ inputs.VERSION }}"
          echo "BUILD_TAG=$TAG" >> $GITHUB_OUTPUT

      - name: Upload To Release
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: /out/packages/pulsar*.pkg*
          release_name: Pulsar Arch Package Release
          body: ${{ steps.description.outputs.BUILD_LOG }}
          tag: ${{ steps.build_tag.outputs.BUILD_TAG }}
          file_glob: true

      - name: Bump Tag
        env:
          PKGVER: ${{ inputs.VERSION }}
        run: sed -i "s/\(Tag=\"\)[^\"]*\"/\1$PKGVER\"/" .tag
      - uses: stefanzweifel/git-auto-commit-action@v5
        env:
          PKGVER: ${{ inputs.VERSION }}
        with:
          skip_checkout: true
          file_pattern: '.tag'
          commit_message: "Pulsar: v$PKGVER"
